version: '3.8'

services:

  node:
    container_name: node
    image: node:21.6.0-alpine3.18
    volumes:
      - ./app:/app
      - node-cache:/usr/local/share/.cache
    working_dir: /app

volumes:
  node-cache:
